[env:esp32-c6-devkitm-1]
platform = espressif32
board = esp32-c6-devkitm-1
framework = espidf
monitor_speed = 115200
upload_port = COM12
monitor_port = COM12
lib_deps = 
    lvgl/lvgl@^8.3.0
